orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, SuccessTemplateView, CanceledTemplateView, OrderListView, OrderDetailView

app_name = 'orders'
urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),
]

products/urls.py
from django.urls import path

from products.views import *

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    # path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('search/', ProductsListView.as_view(), name='search'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView, UserProfile2View)

app_name = 'users'

urlpatterns = [
    path('login_2/', UserLoginView.as_view(), name='login'),
    path('registration_2/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('basket/<int:pk>/', login_required(UserProfile2View.as_view()), name='basket'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

products/models.py
import stripe

from django.db import models
from django.conf import settings

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    stripe_product_price_id = models.CharField(max_length=1000, null=True, blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'Продукт {self.name} | Категория:{self.category.name}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price * 100), currency='BYN')
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum()),
        }
        return basket_item

products/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.shortcuts import HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from products.models import Basket, Product, ProductCategory


class IndexView(TitleMixin, TemplateView):
    template_name = 'products/index.html'
    title = "Магазин"


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 3
    title = 'Магазин - Каталог'
    ordering = ['quantity']

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        queryset = queryset.filter(category_id=category_id) if category_id else queryset

        search_query = self.request.GET.get('q')
        if search_query:
            queryset = queryset.filter(name__icontains=search_query)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategory.objects.all()
        context['q'] = self.request.GET.get('q')
        return context


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

{#    <!-- Custom styles for this template -->#}
    <link href="{% static 'vendor/css/styl.css'%}" rel="stylesheet">

    {% block css %} {% endblock %}
    <!--данный код я вставил -->
        <style>

        .navbar {
            background: black;
        }

        .navbar-nav {
            display: flex;
            justify-content: space-between;
            width: 100%;
        }

        .navbar-collapse {
            margin-left: 100px;
            margin-right: 100px;
        }

        </style>

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Магазин ноутбуков</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fas fa-list"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
            {%  if user.is_authenticated  %}
                <li class="nav-item ">
                    <a class="nav-link text-white " href="{% url 'products:index' %}">Ноутбуки <i class=""></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'users:profile' user.id %}">Профиль <i class=""></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'orders:orders_list' %}">Заказы <i class=""></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'users:basket' user.id %}">Корзина <i class=""></i> </a>
                </li>
                {%  if user.is_superuser or user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="admin/">Админ-панель <i class=""></i> </a>
                    </li>
                {% endif %}
            {% endif %}
            </ul>
        </div>
        <div class="auth-buttons">
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'users:logout' %}">Выйти</a>
            {% else %}
                <a class="navbar-brand" href="{% url 'users:login' %}">Войти</a>
            {% endif %}
        </div>



{#                {%  if user.is_authenticated  %}#}
{#                 <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"#}
{#                       data-bs-toggle="dropdown" aria-expanded="false">#}
{#                        <i class="fas fa-user"></i>#}
{#                    </a>#}
{#                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                        <li>#}
{#                            <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a class="dropdown-item" href="{% url 'orders:orders_list' %}">Заказы</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a class="dropdown-item" href="{% url 'users:basket' user.id %}">Корзина</a>#}
{#                        </li>#}
{#                        {%  if user.is_superuser or user.is_staff %}#}
{#                            <li><a class="dropdown-item" href="admin/">Админ-панель</a></li>#}
{#                        {% endif %}#}
{#                        <li>#}
{#                            <hr class="dropdown-divider">#}
{#                        </li>#}
{#                        <li>#}
{#                            <a class="dropdown-item" href="{% url 'users:logout' %}">#}
{#                                Выйти#}
{#                            </a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </li>#}
{#                {%  else %}#}
{#                    <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'users:login'%}">Войти <i class="fas fa-sign-in-alt"></i></a>#}
{#                </li>#}
{#                {%  endif %}#}

    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

products/templates/products/baskets.html
{% if baskets %}
    <h4 class="col-lg-7 mx-auto">
        <span class="mt-3 mb-3 text-center display-4 font-weight-bold">Корзина</span>
        <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
         <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0" readonly>
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'products:basket_remove' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
    {% endfor %}
            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого:</p>
                    <h4 class="float-right">{{ baskets.total_sum }} руб.</h4>
                </div>
            </div>
            <div class="text-center">
                <div class="text-center">
                    <a class="btn btn-success btn-lg w-100" href="{% url 'orders:order_create' %}">
                        Оформить заказ
                    </a>
                </div>
            </div>
{%  else %}
    <h4 class="mt-3 mb-3 text-center ">
                Корзина пуста
            </h4>
{% endif %}

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
	<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5"></h1>
                <p>


                </p>
{#                <button id="start-purchase-btn" type="button" class="btn btn-lg ">#}
{#                    <a id="start-purchase-link" href="{% url 'products:index' %}">#}
{#                        Каталог#}
{#                    </a>#}
{#                </button>#}
            </div>
        </div>
    </div>
</section>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{%  load static cache%}
{%  load humanize%}
{% load static %}


{% block css %}
	<link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Категории</h1>
            <div class="list-group">
                {% for category in categories %}
                    <a href="{% url 'products:category' category.id %}" class="list-group-item">
                        {{ category.name }}
                    </a>
                {% endfor %}

            </div>

        </div>
        <!-- /.col-lg-3 -->
        <br>
        <br>
        <div class="col-lg-9">
        <div class="search-form">
            <form action="{% url 'products:search' %}" method="get">
                <div class="input-group rounded">
                    <input name="q" type="text" class="form-control rounded" placeholder="Поиск" aria-label="Поиск" aria-describedby="search-addon" />
                    <button type="submit" class="btn btn-primary bg-dark rounded"><i class="fas fa-search text-white"></i></button>
                </div>
            </form>
        </div>
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/1slide.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/2slide.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/3slide.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">

                 {% for product in object_list %}
                    <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt=""
                                 style="object-fit: contain; width: 100%; height: 200px;">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title" style="object-fit: contain; width: 100%; height: 110px;">
                                <a href="#" class="text-dark">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price| intcomma }} руб. </h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success btn-outline-dark"
                               href="{% url 'products:basket_add' product.id %}">
                                Добавить в корзину
                            </a>

                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>


{#            <div class="card">#}
{#                <img class="img1" src="{% static 'vendor/img/3.jpg' %}" alt="">#}
{#                <div class="card-content">#}
{#                    <h4 class="card-title">Ноут</h4>#}
{#                </div>#}
{#            </div>#}













            {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% if category_id %}&category={{ category_id }}{% endif %}{% else %}#{% endif %}"
                           tabindex="-1" aria-disabled="true">
                            <
                        </a>
                    </li>
                    {% for page in paginator.page_range %}
                        <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                            <a class="page-link" href="?page={{ page }}{% if category_id %}&category={{ category_id }}{% elif q %}&q={{ q }}{% endif %}">{{ page }}</a>
                        </li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% if category_id %}&category={{ category_id }}{% endif %}{% else %}#{% endif %}">
                            >
                        </a>
                    </li>
                </ul>
            </nav>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <style>
        /* CSS код для переливающегося градиента */

        .py-5 {
            background: black;
        }

        </style>
<footer class="py-5">
    <div class="container">
        <p class="m-0 text-center text-white"></p>
        <div class="row">
            <br/><br/>
            <div class="col-md-12">
                <p class="text-center">
                    <a href="https://github.com/Sashaaasssss" target="_blank" class="btn-social btn-github"><i class="fab fa-github fa-3x"></i></a>
                    <a href="https://instagram.com/sasha__bazhenov__?igshid=MzMyNGUyNmU2YQ==" target="_blank" class="btn-social btn-instagram"><i class="fab fa-instagram fa-3x"></i></a>
                    <a href="tel:+375336684769" class="btn-social btn-phone"><i class="fas fa-phone fa-3x"></i></a>
                </p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}